### ISSUE TITLE
Unable to perform multipart upload after upgrade: current throughput: 0 B/s is below minimum: 1 B/s

### ISSUE THREAD

**Issue by DimanNe** [awslabs/aws-sdk-rust#1146]
### Describe the bug

After this upgrade:
```
aws-config   1.3.0 -> 1.4.0
aws-sdk-s3   1.25.0 -> 1.28.0
aws-smithy-types 1.1.8 -> 1.1.9
```

multi-part upload started to fail with the following messages in logs:

```
[2024-05-13T22:40:02.459500Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-05-13T22:40:02.459541Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-05-13T22:40:02.461266Z DEBUG hyper::proto::h1::dispatch] error writing: Connection reset by peer (os error 104)

[2024-05-13T22:40:02.661296Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-05-13T22:40:02.661314Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-05-13T22:40:02.664376Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-05-13T22:40:02.664381Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] grace period ended; timing out request
[2024-05-13T22:40:02.664390Z DEBUG aws_smithy_runtime::client::orchestrator] encountered orchestrator error; halting
[2024-05-13T22:40:02.664394Z DEBUG tracing::span] finally_attempt;
[2024-05-13T22:40:02.664409Z DEBUG aws_smithy_runtime::client::retries::strategy::standard] not retrying because we are out of attempts attempts=3 max_attempts=3
[2024-05-13T22:40:02.664414Z DEBUG aws_smithy_runtime::client::orchestrator] a retry is either unnecessary or not possible, exiting attempt loop
[2024-05-13T22:40:02.664417Z DEBUG tracing::span] finally_op;
```

Same code works perfectly fine with the older version.

### Expected Behavior

see above

### Current Behavior

see above

### Reproduction Steps

see above

### Version

```text
├── aws-config v1.4.0
│   ├── aws-credential-types v1.2.0
│   │   ├── aws-smithy-async v1.2.1
│   │   ├── aws-smithy-runtime-api v1.6.0
│   │   │   ├── aws-smithy-async v1.2.1 (*)
│   │   │   ├── aws-smithy-types v1.1.9
│   │   ├── aws-smithy-types v1.1.9 (*)
│   ├── aws-runtime v1.2.2
│   │   ├── aws-credential-types v1.2.0 (*)
│   │   ├── aws-sigv4 v1.2.1
│   │   │   ├── aws-credential-types v1.2.0 (*)
│   │   │   ├── aws-smithy-eventstream v0.60.4
│   │   │   │   ├── aws-smithy-types v1.1.9 (*)
│   │   │   ├── aws-smithy-http v0.60.8
│   │   │   │   ├── aws-smithy-eventstream v0.60.4 (*)
│   │   │   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   │   │   ├── aws-smithy-types v1.1.9 (*)
│   │   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   │   ├── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-smithy-async v1.2.1 (*)
│   │   ├── aws-smithy-eventstream v0.60.4 (*)
│   │   ├── aws-smithy-http v0.60.8 (*)
│   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   ├── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-types v1.2.1
│   │   │   ├── aws-credential-types v1.2.0 (*)
│   │   │   ├── aws-smithy-async v1.2.1 (*)
│   │   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   │   ├── aws-smithy-types v1.1.9 (*)
│   ├── aws-sdk-sso v1.24.0
│   │   ├── aws-credential-types v1.2.0 (*)
│   │   ├── aws-runtime v1.2.2 (*)
│   │   ├── aws-smithy-async v1.2.1 (*)
│   │   ├── aws-smithy-http v0.60.8 (*)
│   │   ├── aws-smithy-json v0.60.7
│   │   │   └── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-smithy-runtime v1.5.0
│   │   │   ├── aws-smithy-async v1.2.1 (*)
│   │   │   ├── aws-smithy-http v0.60.8 (*)
│   │   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   │   ├── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   ├── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-types v1.2.1 (*)
│   ├── aws-sdk-ssooidc v1.25.0
│   │   ├── aws-credential-types v1.2.0 (*)
│   │   ├── aws-runtime v1.2.2 (*)
│   │   ├── aws-smithy-async v1.2.1 (*)
│   │   ├── aws-smithy-http v0.60.8 (*)
│   │   ├── aws-smithy-json v0.60.7 (*)
│   │   ├── aws-smithy-runtime v1.5.0 (*)
│   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   ├── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-types v1.2.1 (*)
│   ├── aws-sdk-sts v1.24.0
│   │   ├── aws-credential-types v1.2.0 (*)
│   │   ├── aws-runtime v1.2.2 (*)
│   │   ├── aws-smithy-async v1.2.1 (*)
│   │   ├── aws-smithy-http v0.60.8 (*)
│   │   ├── aws-smithy-json v0.60.7 (*)
│   │   ├── aws-smithy-query v0.60.7
│   │   │   ├── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-smithy-runtime v1.5.0 (*)
│   │   ├── aws-smithy-runtime-api v1.6.0 (*)
│   │   ├── aws-smithy-types v1.1.9 (*)
│   │   ├── aws-smithy-xml v0.60.8
│   │   ├── aws-types v1.2.1 (*)
│   ├── aws-smithy-async v1.2.1 (*)
│   ├── aws-smithy-http v0.60.8 (*)
│   ├── aws-smithy-json v0.60.7 (*)
│   ├── aws-smithy-runtime v1.5.0 (*)
│   ├── aws-smithy-runtime-api v1.6.0 (*)
│   ├── aws-smithy-types v1.1.9 (*)
│   ├── aws-types v1.2.1 (*)
├── aws-sdk-s3 v1.28.0
│   ├── aws-credential-types v1.2.0 (*)
│   ├── aws-runtime v1.2.2 (*)
│   ├── aws-sigv4 v1.2.1 (*)
│   ├── aws-smithy-async v1.2.1 (*)
│   ├── aws-smithy-checksums v0.60.7
│   │   ├── aws-smithy-http v0.60.8 (*)
│   │   ├── aws-smithy-types v1.1.9 (*)
│   ├── aws-smithy-eventstream v0.60.4 (*)
│   ├── aws-smithy-http v0.60.8 (*)
│   ├── aws-smithy-json v0.60.7 (*)
│   ├── aws-smithy-runtime v1.5.0 (*)
│   ├── aws-smithy-runtime-api v1.6.0 (*)
│   ├── aws-smithy-types v1.1.9 (*)
│   ├── aws-smithy-xml v0.60.8 (*)
│   ├── aws-types v1.2.1 (*)
├── aws-smithy-types v1.1.9 (*)

```

### Environment details (OS name and version, etc.)

Linux

**Comment by Smotrov** [comment]
Same error with `SQS`

**Comment by aajtodd** [comment]
Thanks for the issue, we are looking into this now and how best to address it.

--- 

As a workaround you can disable `upload` throughput protection:

```rust
    let config = aws_config::defaults(aws_config::BehaviorVersion::latest())
        .stalled_stream_protection(
            StalledStreamProtectionConfig::enabled()
                .upload_enabled(false)
                .build(),
        )
        .load()
        .await;
```

This will keep stalled stream protection for downloads enabled and only disable uploads (which was the default prior to `BehaviorVersion::v2024_03_28()`). If you want to disable it completely for uploads and downloads:

```rust
    let config = aws_config::defaults(aws_config::BehaviorVersion::latest())
        .stalled_stream_protection(StalledStreamProtectionConfig::disabled())
        .load()
        .await;
```

**Comment by Velfi** [comment]
We just released the runtime crate updates: https://github.com/smithy-lang/smithy-rs/releases/tag/release-2024-05-21
Once a release for the SDK crates runs later today _(in about two hours)_ they'll include this fix.

**Comment by ysaito1001** [comment]
Let us know whether [today's release](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2024-05-22) has improved the behavior of your use case.

**Comment by kolupaev** [comment]
Hi Folks, unfortunately latest update didn't resolve the issue. Large multi-part uploads still fail in the same way on the slow-ish internet: 

```

RUST_LOG=debug cargo run --  -o text -i ~/Downloads/not_so_humongous_video.mp4

2024-08-16T16:00:21Z DEBUG hyper::proto::h1::io] flushed 4096 bytes
[2024-08-16T16:00:21Z DEBUG hyper::proto::h1::io] flushed 4096 bytes
[2024-08-16T16:00:21Z DEBUG hyper::proto::h1::io] flushed 4096 bytes
[2024-08-16T16:00:21Z DEBUG hyper::proto::h1::io] flushed 4096 bytes
[2024-08-16T16:00:21Z DEBUG hyper::proto::h1::io] flushed 4096 bytes
[2024-08-16T16:00:21Z DEBUG hyper::proto::h1::io] flushed 3732 bytes
⠦ Using bucket region us-east-1[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
⠖ Using bucket region us-east-1[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
⠒ Using bucket region us-east-1[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
⠐ Using bucket region us-east-1[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] current throughput: 0 B/s is below minimum: 1 B/s
[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::http::body::minimum_throughput] grace period ended; timing out request
[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::orchestrator] encountered orchestrator error; halting
[2024-08-16T16:00:21Z DEBUG tracing::span] finally_attempt;
[2024-08-16T16:00:21Z DEBUG rustls::common_state] Sending warning alert CloseNotify
[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::retries::strategy::standard] not retrying because we are out of attempts attempts=3 max_attempts=3
[2024-08-16T16:00:21Z DEBUG aws_smithy_runtime::client::orchestrator] a retry is either unnecessary or not possible, exiting attempt loop
[2024-08-16T16:00:21Z DEBUG tracing::span] finally_op;
Error: Failed to upload to S3

Caused by:
    0: dispatch failure
    1: timeout
    2: minimum throughput was specified at 1 B/s, but throughput of 0 B/s was observed

```
